In [35]:
## Packages needed for this exercise
import numpy as np
import decimal
import math

## Setting

In this exercise, we work on practice questions on `array` object. 

## Q1. [8 Points]


* `Decimal(a)` function inside `decimal` module can be used to print the actual value of float `a` stored on the computer.

> For example when you use `decimal.Decimal(0.1)`, the output will be `Decimal('0.1000000000000000055511151231257827021181583404541015625')`

* `ceil(b)` function inside `math` module can be used to perform the ceil operation on `b`. 




Use these two functions to demonstrate the following
`np.arange(1,1.3,0.1)`
and `np.arange(1,1.4,0.1)` both returns 1, 1.1, 1.2, and 1.3. Make sure to carely show the following:

* (1) Compute the number of elements in concluded 
* (2) Demonstrate **WHY** the number of elements is the same in both cases.
* (3) After we compute the number of elements, how  is the sequence of numbers determined? 



In [36]:
decimal.Decimal(1.3)

Decimal('1.3000000000000000444089209850062616169452667236328125')

In [37]:
decimal.Decimal(1.4)

Decimal('1.399999999999999911182158029987476766109466552734375')

In [38]:
# the number of elements are the same in both case is because the stop element is not included and 1.3 is actually larger than 1.3 determined by the Decimal method and 1.4 is smaller than 1.4
# since the stop elememt is not included 1.3 would be the last of  np.arange(1,1.3,0.1) because the stop is larger than 1.3. np.arange(1,1.4,0.1) has the same stop element because 1.4 is actually between 1.3 and 1.4 

In [39]:
math.ceil((decimal.Decimal((1.3-1)/0.1)) )


4

In [40]:
math.ceil((decimal.Decimal((1.4-1)/0.1)) )

4

In [41]:
#using math.ceil we can determine how many steps/elements needed and the sequence is incremented each time by the step value 

## Q2. [3 points]

Let's generate the following one-dimensional array using 3 different methods: 

$$-1, -1.2, -1.4, -1.6, -1.8$$


(1) Use `np.array` function  

(2) Use `np.arange` function  

(3) Use `np.linspace` function  

 

       


In [42]:
a= [-1,-1.2,-1.4,-1.6,-1.8]
a= np.array(a)
print (a)

[-1.  -1.2 -1.4 -1.6 -1.8]


In [43]:
a= np.arange(-1, -2, -0.2)
print (a)

[-1.  -1.2 -1.4 -1.6 -1.8]


In [44]:
a= np.linspace(-1, -2, 5, False)
print (a)

[-1.  -1.2 -1.4 -1.6 -1.8]


In [45]:
 # linsapce and arange automatically creats an array 

## Q3. [8 Points]

* Generate the following two-dimensional array `A1`

$$\begin{matrix} 
1& 4 & 6  \\
2& 5 & 7  \\
3& 6 & 9 \\
\end{matrix}$$


* `size` is an attribute for `array` object, which returns the number of elements an array object has. Use `size` attribute to report the number of elements in the array `A1`. 

* With the help of `shape` attribute, report the number of elements in the array `A1`.  

* Study `np.fill_diagonal()` function and `NumPy` `copy()` method. Create 2 arrays:

>* A2: Same value as A1 except for all diagonal elements are equal to 10.  
>* A1: Should stay unchanged.










In [46]:
A1=np.array([[1,4,6],[2,5,7],[3,6,9]])

In [47]:
A1.size

9

In [49]:
np.prod(A1.shape) 

9

In [15]:
A2 = A1.copy()
np.fill_diagonal(A2,10) 
print(A2), print (A1)

[[10  4  6]
 [ 2 10  7]
 [ 3  6 10]]
[[1 4 6]
 [2 5 7]
 [3 6 9]]


(None, None)

## Q4. [5 Points]

* Create `A3`, a copy of `A1`

* Use slicing on both dimensions (`Array[::,::]`), retrieve the following  2-dimenional array from `A3` array. 

$$\begin{matrix} 
3& 9 \\
2& 7  \\
\end{matrix}$$

* Based on the previous step,   replace `3, 9 , 2, 7` with  `1, 2, 3, 4` respectively in `A3`. The final array should be 

$$\begin{matrix} 
1& 4 & 6  \\
3& 5 & 4  \\
1& 6 & 2 \\
\end{matrix}$$




In [16]:
A3 = A1.copy()
print(A3)

[[1 4 6]
 [2 5 7]
 [3 6 9]]


In [17]:
A3[2:0:-1, 0:3:2]


array([[3, 9],
       [2, 7]])

## Q5. [5 Points]

* Create `A4`, a copy of `A1`

* Based `Array[[],[]]`, retrieve the following  1-dimenional array from `A4` array. 

$$3, 9, 2, 7$$

* Based on the previous step, replace `3, 9 , 2, 7` with `1, 2, 3, 4` respectively in`A4`. 

The final array should be 

$$\begin{matrix} 
1& 4 & 6  \\
3& 5 & 4  \\
1& 6 & 2 \\
\end{matrix}$$



In [18]:

A4=A1.copy()
A4[[2,2,1,1], [0,2,0,2]]


array([3, 9, 2, 7])

In [19]:
A4[[2,2,1,1], [0,2,0,2]] = np.array([1,2,3,4])
print(A4)

[[1 4 6]
 [3 5 4]
 [1 6 2]]


## Q6. [6 Points]

From A1, retrieve $6,5$ following two steps:

* Swap the last two columns, which gives 
$$\begin{matrix} 
1& 6&4    \\
2& 7& 5     \\
3& 9& 6    \\
\end{matrix}$$


* For the updated array, retrieve the following using slicing 
$$\begin{matrix} 
6 & 4  \\
7 & 5  \\
\end{matrix}$$ 

* Use a `NumPy` function to retrieve the two diagonal element from the previous array. 

* Use comparison operation and Boolean operator to return `True` if at least one of the following statements is True. Otherwise, return `False`.

>* The first diagonal element we got from the last step is lower than 3
>* The second diagonal element we got from the last step is higher than 4.





In [20]:
print(A1)

[[1 4 6]
 [2 5 7]
 [3 6 9]]


In [21]:
A1_new = A1 [ :: , [0,2,1]]
print(A1_new)

[[1 6 4]
 [2 7 5]
 [3 9 6]]


##

In [22]:
A1_new[0:2:, 1:3:]

array([[6, 4],
       [7, 5]])

In [23]:
np.diag (A1_new[0:2:, 1:3:])


array([6, 5])

In [24]:
diag = np.diag (A1_new[0:2:, 1:3:])
diag[0]<3 or diag[1] >4

True