In [27]:
import numpy as np
import pandas as pd
import pickle
import math
with open('Return', 'rb') as handle:
    Return = pickle.load(handle)


## Setting

An analyst needs to do the business planning using array `Return`. 

* Each column represents a department. From left to right: `D1`, `D2`, ...
* Each rows represents a business plan. From top to bottom: `P1`, `P2`, ...
* Each cell represents the return if a department adopts a business plan.  
* If a plan is not feasible for a department, the analyst uses 999 for the return, which is much higher than the highest possible return.

**Your answer should NOT be based on eye-balling. In other words, if we change the data set by adding more rows or columns, your result should be robust enough to handle the different data set.** 

In [28]:
Return

array([[999,  16,  15,   1,  -2],
       [ 18,   9, 999,  18,  20],
       [999,  15,  -2,   5,  15],
       [  4, 999,  -1,  15, 999],
       [  1,  13, 999, 999,  12],
       [999, 999,   9,  20, 999],
       [  1,   7,  12,   7, 999],
       [999, 999,   2, 999,  20],
       [ 10, 999,  12,   5,  -1],
       [  9,  13, 999, 999,  18]])

## Q1. [4 Points] 

Create the following two string arrays to store department names and 

* Department: `D1`, `D2`, `D3`, ...
* Plan: `P1`, `P2`, `P3`, ...

Through the exercise, whenever we ask "which department" or "which plan", please report the string name instead of the index.



In [29]:
shape = Return.shape
number = np.arange (1, shape[1]+1)
Department= np.char.add("D", number.astype(str))
number2 = np.arange (1, shape[0]+1)
Plan= np.char.add("P", number2.astype(str))

## Q2. [10 Points]

* Among all the **unique** return values from the feasible plans, what is the 4th highest value? 

* Find all the department/plan combinations that give this value. Report the combinations in an array that contains `Dx:Py`, `Dx:Py`, ... using `np.char`. For example, `["D1:P1", "D3:P3"]`  The order of the elements does not matter. 

In [40]:
Return_2 = np.where (Return == 999, np.nan, Return)
print(Return_2)
R= np.sort(np.unique (Return_2))[-5]

print(R)


[[nan 16. 15.  1. -2.]
 [18.  9. nan 18. 20.]
 [nan 15. -2.  5. 15.]
 [ 4. nan -1. 15. nan]
 [ 1. 13. nan nan 12.]
 [nan nan  9. 20. nan]
 [ 1.  7. 12.  7. nan]
 [nan nan  2. nan 20.]
 [10. nan 12.  5. -1.]
 [ 9. 13. nan nan 18.]]
15.0


In [54]:

p =Plan[np.where (Return == R)[0]]
d = Department[np.where (Return == R)[1]]
print(d)

['D3' 'D2' 'D5' 'D4']


In [55]:
p= np.char.add(p.astype(str), ":")
np.char.add(p, d.astype(str))

array(['P1:D3', 'P3:D2', 'P3:D5', 'P4:D4'], dtype='<U45')

## Q3. [14 Points]

 
* Find the best feasible plan for each department. Report the information using a `DataFrame` with the following format. The correct answer could differ from the cell values. Only report one plan for each department if there are ties. 

<table>
    <tr>
        <th></th>
        <th>Department</th>
        <th>BestPlan</th>
    </tr>
    <tr>
        <th>0</th>
        <td>D1</td>
        <td>P2</td>
    </tr>
    <tr>
        <th>1</th>
        <td>D2</td>
        <td>P2</td>
    </tr>
    <tr>
        <th>2</th>
        <td>D3</td>
        <td>P3</td>
    </tr>
        <tr>
        <th>3</th>
        <td>D4</td>
        <td>P2</td>
    </tr>
        <tr>
        <th>4</th>
        <td>D5</td>
        <td>P4</td>
    </tr>
</table>


* Report the total profit under the strategy you found.

* There might be ties. Find how many strategies each department has to achieve the same total profit. Present the result in a `DataFrame` with the following format. The correct answer could differ from the cell values.

<table>
    <tr>
        <th></th>
        <th>Department</th>
        <th>NumberOfPlans</th>
    </tr>
    <tr>
        <th>0</th>
        <td>D1</td>
        <td>2</td>
    </tr>
    <tr>
        <th>1</th>
        <td>D2</td>
        <td>2</td>
    </tr>
    <tr>
        <th>2</th>
        <td>D3</td>
        <td>1</td>
    </tr>
        <tr>
        <th>3</th>
        <td>D4</td>
        <td>1</td>
    </tr>
        <tr>
        <th>4</th>
        <td>D5</td>
        <td>1</td>
    </tr>
</table>



In [9]:

bp = np.nanargmax(Return_2, axis = 0)
print(bp)

bp_plan =Plan[bp]
best_plan = {"Department":Department, "BestPlan": bp_plan}
best_plan = pd.DataFrame(best_plan)
display(best_plan)

[1 0 0 5 1]


Department BestPlan
0         D1       P2
1         D2       P1
2         D3       P1
3         D4       P6
4         D5       P2

In [10]:
profit = np.nanmax(Return_2, axis = 0)
print ("max profit each Department: ", profit)

total_profit = np.sum(profit)
total_profit
#number = np.unique (Return[Return == profit], return_counts=True )
#numberOfPlan = {"Department":Department, "NumberOfPlans": number}

max profit each Department:  [18. 16. 15. 20. 20.]


89.0

In [11]:
#Report the total profit under the strategy you found.

In [12]:
 # number of strategies to achieve same profit

In [13]:
repeats = np.sum(Return == profit, axis = 0)
NumberOfPlans = {"Department":Department, "NumberOfPlans": repeats}
NumberOfPlans = pd.DataFrame(NumberOfPlans)
display(NumberOfPlans)

Department  NumberOfPlans
0         D1              1
1         D2              1
2         D3              1
3         D4              1
4         D5              2

## Q4. [10 Points]

The analyst aims to find a combination with the second-highest total return value. To do so, she needs to see which department can get the smallest **non-zero** drop in total return if she assigns a different plan to the department.

* Find one combination that satisfies the statement. Report the information using a `DataFrame` with the following format. The correct answer could differ from the cell values. Only report one plan for each department if there are ties. 

<table>
    <tr>
        <th></th>
        <th>Department</th>
        <th>BestPlan</th>
    </tr>
    <tr>
        <th>0</th>
        <td>D1</td>
        <td>P2</td>
    </tr>
    <tr>
        <th>1</th>
        <td>D2</td>
        <td>P2</td>
    </tr>
    <tr>
        <th>2</th>
        <td>D3</td>
        <td>P3</td>
    </tr>
        <tr>
        <th>3</th>
        <td>D4</td>
        <td>P2</td>
    </tr>
        <tr>
        <th>4</th>
        <td>D5</td>
        <td>P4</td>
    </tr>
</table> 

* Report the total profit under this combination.
 

 


In [15]:

Return_3 = Return_2.copy()
# get rid of the max 
Return_3 = np.where (Return_3 == profit, np.nan, Return_3)
#print(np.sort(Return_3))
difference =  profit - Return_3
print(difference)
loc = np.nanmin(difference)
arr = np.array(np.where(difference == loc))
print(arr)
plan_2 = Plan[arr[0]]


bp_plan2 = bp_plan.copy()

bp_plan2[arr[1]] = plan_2


best_plan2 = {"Department":Department, "BestPlan": bp_plan2}
best_plan2 = pd.DataFrame(best_plan2)
display(best_plan2)
 

[[nan nan nan 19. 22.]
 [nan  7. nan  2. nan]
 [nan  1. 17. 15.  5.]
 [14. nan 16.  5. nan]
 [17.  3. nan nan  8.]
 [nan nan  6. nan nan]
 [17.  9.  3. 13. nan]
 [nan nan 13. nan nan]
 [ 8. nan  3. 15. 21.]
 [ 9.  3. nan nan  2.]]
[[2]
 [1]]


Department BestPlan
0         D1       P2
1         D2       P3
2         D3       P1
3         D4       P6
4         D5       P2