In [1]:
import numpy as np
import pandas as pd 
import pickle

In [2]:
file = open('Q3Data', 'rb')
Data=pickle.load(file)
Sales=Data["Sales"] 

## Setting
Sales array stores the sales over several weeks. For the last observational week, only sales from the first few days are observed. The sales are recorded in `Sales` array. The first 7 numbers give the daily sales from the first week. The next 7 numbers give the daily sales from the second week. ...

In [3]:
Sales

array([4, 7, 7, 6, 0, 5, 3, 4, 5, 1, 2, 5, 6, 6, 6, 0, 0, 6, 1, 2, 6, 7,
       4, 1, 6, 3, 5, 6, 3, 3, 5, 5, 2, 0, 6, 3, 2, 4, 2, 2, 5, 4, 2, 3,
       2, 4, 1, 4, 6, 1, 5, 3, 6, 6, 6, 4, 5, 5, 3, 4, 4, 0, 5, 4, 6, 3,
       3])

## Q1. [6 Points]


* Do the following to help the analyst calculate the total sales for each week.  

> * Construct a 2-dimensional array `Sales2` from the 1-dimensional `Sales` array. Each row in `Sales2` represents a week, while each column represents a day of the week. For the last few days with unobserved sales, record `np.nan`. 





In [4]:
Sales2 = np.append(Sales, np.repeat(np.nan, 7-len(Sales)%7))
Sales2 = Sales2.reshape(-1, 7)
Sales2

array([[ 4.,  7.,  7.,  6.,  0.,  5.,  3.],
       [ 4.,  5.,  1.,  2.,  5.,  6.,  6.],
       [ 6.,  0.,  0.,  6.,  1.,  2.,  6.],
       [ 7.,  4.,  1.,  6.,  3.,  5.,  6.],
       [ 3.,  3.,  5.,  5.,  2.,  0.,  6.],
       [ 3.,  2.,  4.,  2.,  2.,  5.,  4.],
       [ 2.,  3.,  2.,  4.,  1.,  4.,  6.],
       [ 1.,  5.,  3.,  6.,  6.,  6.,  4.],
       [ 5.,  5.,  3.,  4.,  4.,  0.,  5.],
       [ 4.,  6.,  3.,  3., nan, nan, nan]])

## Q2 [4 Points]

[`np.all`](https://numpy.org/doc/stable/reference/generated/numpy.all.html) is a function that tests whether all array elements along a given axis evaluate to True. 

[`np.any`](https://numpy.org/doc/stable/reference/generated/numpy.all.html) is a function that tests whether at least one array element along a given axis evaluate to True. 

* Based on `np.any`, create a Boolean array of values corresponding to each week. The Boolean value should give:
>* True: at least one observed day in the week has non-zero sales. 
> * False: Every observed day in the week has zero sales. 
* Perform the previous task using `np.all`.
 

In [5]:
np.any((Sales2!=0), axis = 1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [8]:
#how to return true with all when only one has non zero 
~(np.all((Sales2==0), axis = 1))

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])